### PR TITLE
Fixed functools.partial fix in Cifar10 notebook

### PR DESCRIPTION
**Pull request by xchoo**
Replaced functools.partial call with proper function definitions. Addresses issue #313.

### CODE REVIEW

**Comment by hunse** [comment]
Why?

**Comment by xchoo** [comment]
Updated description with issue number.

**Comment by hunse** [comment]
Also now setting the learning phase using the NengoDL method that works with newer TensorFlow.

**Review by tbekolay — APPROVED** [review]
LGTM, runs locally without (unexpected) warnings. I also added the params.npz file to `.gitignore`. Merging when CI is happy.

**Pull request merged**
