### PR TITLE
Force Loihi solvers to weights=True

### PR DESCRIPTION
**Pull request by tcstewar**
This is an initial attempt at implementing a way to force nengo-loihi to do full connection weight matrices rather than whatever the solver says.

I'm posting this not as a polished PR, but rather to get feedback on whether this seems to be the right way to go about implementing this.

As discussed in #72, this cannot be done by adjusting nengo defaults, since nengo currently does not allow you to set a solver with weights=True when you have a Node involved in the Connection.  Furthermore, even if you could do that, with the advent of #64 , we'll be removing the passthrough nodes from models, so the Ensemble->Ensemble connection that we want to have weights=True for won't even exist at that time.  For these reasons, I've implemented this forcing of using weights=True as part of the builder itself.

TODO:
 - [ ] Discuss whether this is the best approach
 - [ ] Write some unit tests
 - [ ] Analyze the effects on accuracy and memory usage for a few benchmark models

### CODE REVIEW

**Comment by tcstewar** [comment]
(note: this is branched off of `limit-intercepts`, so just look at the most recent commit for the changes done here)

**Comment by drasmuss** [comment]
Xuan seems to be getting worse behaviour with `weights=True` in #90, so we should figure out why that is before we force `weights=True`.

**Comment by hunse** [comment]
This was more of an issue before we improved the DecodeNeurons (#132).

**Comment by tbekolay** [comment]
As @hunse says, this is less of an issue now, and this part of the code has changed a bunch so rebasing will be difficult. It's still possible to do this across the model by changing the default solver to a `weights=True` solver, so I'm going to close this.

**Comment by arvoelke** [comment]
> As @hunse says, this is less of an issue now, and this part of the code has changed a bunch so rebasing will be difficult.

Do we have anything in place (or an open issue) to test the difference between `weights=True` and `weights=False` to help spot a regression, and as a basis for future improvements?

> It's still possible to do this across the model by changing the default solver to a `weights=True` solver, so I'm going to close this.

As @tcstewar said in the original post this doesn't work for any model which contains a node (which is basically every model that we have). e.g.,

```python
import nengo
with nengo.Network() as model:
    model.config[nengo.Connection].solver = nengo.solvers.LstsqL2(weights=True)
    nengo.Connection(nengo.Node(0), nengo.Ensemble(1, 1))
```

```
nengo.exceptions.ValidationError: Connection.solver: weight solvers only work for connections from ensembles (got 'Node')
```

**Comment by tbekolay** [comment]
> Do we have anything in place (or an open issue) to test the difference between `weights=True` and `weights=False` to help spot a regression, and as a basis for future improvements?

I don't believe that we do, but also I didn't search for it. Feel free to make a new issue if it hasn't been tracked though -- we're trying to keep our PR queue to a minimum so we would prefer new issues over keeping PRs open as a reminder of some issue.

> this doesn't work for any model which contains a node

Good point. You can still change it on a per-connection basis, but you can't set it as a default.

**Pull request closed without merging**
