### PR TITLE
Neuron to neuron examples

### PR DESCRIPTION
**Pull request by tbekolay**
A notebook with three example networks using direct neuron-to-neuron connections. Here are the plots from the notebook if you don't want to run it yourself:

* Simple fan-out with Nengo

1-nengo

* Simple fan-out with Nengo Loihi

1-loihi

* One-to-one connections with Nengo

2-nengo

* One-to-one connections with Nengo Loihi

2-loihi

* Fixed probability connections with Nengo

3-nengo

* Fixed probability connections with Nengo Loihi

3-loihi

This was originally going to be part of #23 (and therefore is based on it), but I ran into an issue so I figured I would split this off into a separate PR so that it doesn't block the release (if we manage to figure it out in time though, we can include it).

The issue is that when making neuron-to-neuron connection in Nengo Loihi, the transform matrix has to be scaled up by `1 / dt` (at least, scaling up by 1000 worked, so I assume it's a `1 / dt` scaling problem). This means that you can't run the same model in Nengo and expect it to work in Nengo Loihi if you're using direct neuron-to-neuron connections, which is a pretty big issue.

I'll start looking into this tomorrow, but if anyone knows why this might be the case (or how it can be fixed), help would be appreciated.

### CODE REVIEW

**Comment by drasmuss** [comment]
There used to be a 1/dt scaling on neuron connections, but I had to remove
it to get the other neuron-neuron test to work properly (the amplitude
one). I notice that one difference is that that test has synapse=none and
these ones don't, so maybe it has something to do with how synapses are
implemented? E.g. perhaps the dt scaling is being implemented in the
synaptic filtering, rather than the voltage accumulation, so you get a
dramatic change in behaviour with synapse=none? That's just a guess.

**Comment by drasmuss** [comment]
Update: figured out it has to do with the `RectifiedLinear` implementation.  Currently `RectifiedLinear` does not scale its voltage accumulation by `dt` (which is why we needed to scale the connection weights by `dt` to get the correct behaviour).  This is probably related to #10.  Going to see if I can figure out how to fix `RectifiedLinear`, but in case it isn't straightforward I'd say we just put the `1/dt` scaling on connection weights back in and `xfail` the RectifiedLinear tests, so that we can get this merged.

**Comment by tbekolay** [comment]
Agreed, better to release without ReLu support than with this bug.

**Comment by tbekolay** [comment]
OK I pushed a commit disabling ReLu and the associated tests, and reverting the weight scaling change commit. With this, the neuron-to-neuron connections look good in the emulator; running things on Loihi now.

**Comment by tbekolay** [comment]
This also I would like in the release I'm planning for Monday so could someone please review this soon.

**Comment by drasmuss** [comment]
I was trying to figure out why the `test_ens_neurons_on_host` test was failing, but no success yet.  I think it's OK not to block the release on that, but maybe we could put the old test back in (in place of or in addition to the reverted one) and xfail it so we have a note/test case showing something weird going on there?

**Comment by tbekolay** [comment]
Yeah sounds good, I'll add in the old one alongside this one.

**Comment by tbekolay** [comment]
After a bit of discussion, @drasmuss and I are pretty sure that the reason the old test is failing is because seeds change when moving the ensemble on/off chip, which is the main difference between the two tests (one sampled the parameters beforehand, the other let Nengo sample the parameters). Instead of adding back the old test, which is mostly a duplication of this one, I added a parameter as to whether we should seed the ensemble itself and `xfail`ed the case when the ensembles weren't seeded but the network is seeded.

**Pull request merged**
